name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        else
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        fi
      shell: bash
        
    - name: Build with PyInstaller
      run: |
        python build.py
        
    - name: Generate changelog
      id: changelog
      run: |
        # 获取最近的两个标签
        CURRENT_TAG="${{ github.ref }}"
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 "${CURRENT_TAG}^" 2>/dev/null || echo "")
        
        if [ -n "$PREVIOUS_TAG" ]; then
          # 如果存在前一个标签，获取两个标签之间的提交
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "### 更新内容" >> $GITHUB_ENV
          git log --pretty=format:"- %s" ${PREVIOUS_TAG}..${CURRENT_TAG} >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        else
          # 如果是第一个标签，获取所有提交
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "### 首次发布" >> $GITHUB_ENV
          git log --pretty=format:"- %s" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi
      shell: bash
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      with:
        name: Release ${{ env.VERSION }}
        tag_name: v${{ env.VERSION }}
        body: |
          文件分类助手 v${{ env.VERSION }}
          
          ### 系统要求
          - Windows 10 或更高版本
          - 需要安装 Tesseract OCR 和 FFmpeg（首次运行时会自动下载）
          
          ${{ env.CHANGELOG }}
          
        files: |
          dist/FileClassifier.exe
        draft: false
        prerelease: ${{ contains(env.VERSION, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: FileClassifier-${{ env.VERSION }}
        path: dist/FileClassifier.exe 